import { useSyncExternalStore } from 'react'
import { supabase } from './supabase'

// Player identity — a lightweight "Player Pass". A profile is a first + last
// name plus a short, friendly pass code (e.g. EXTRA-4F7Q) generated by the
// server. It's remembered in this browser so a player isn't re-prompted, and
// the pass code lets them re-attach to the same profile on another device.
// No accounts, no passwords, no PII beyond the name they already give.

export type Profile = {
  id: string
  passCode: string
  firstName: string
  lastName: string
}

const KEY = 'extra-mile-profile'
const LEGACY_KEY = 'extra-mile-player' // pre-profiles name-only storage

// A tiny reactive store so the whole app (header badge, game page) reflects
// sign-in / sign-out immediately, without a page reload. `current` caches the
// loaded profile; `listeners` are React subscribers via useProfile().
let current: Profile | null | undefined // undefined = not loaded yet
const listeners = new Set<() => void>()
const emit = () => listeners.forEach((l) => l())

function readStorage(): Profile | null {
  try {
    const raw = localStorage.getItem(KEY)
    if (!raw) return null
    const p = JSON.parse(raw) as Profile
    if (p && p.id && p.passCode && p.firstName && p.lastName) return p
    return null
  } catch {
    return null
  }
}

export function getProfile(): Profile | null {
  if (current === undefined) current = readStorage()
  return current
}

function store(p: Profile): void {
  current = p
  try {
    localStorage.setItem(KEY, JSON.stringify(p))
    localStorage.removeItem(LEGACY_KEY)
  } catch {
    /* private mode / storage disabled — the app still works for this session */
  }
  emit()
}

export function clearProfile(): void {
  current = null
  try {
    localStorage.removeItem(KEY)
  } catch {
    /* ignore */
  }
  emit()
}

/** React hook: the current profile, re-rendering on sign-in / sign-out. */
export function useProfile(): Profile | null {
  return useSyncExternalStore(
    (cb) => {
      listeners.add(cb)
      return () => listeners.delete(cb)
    },
    getProfile,
    getProfile,
  )
}

export function fullName(p: Profile): string {
  return `${p.firstName} ${p.lastName}`.trim()
}

// Normalize whatever the player types into a pass code: uppercase, trim, drop
// stray spaces, and add the EXTRA- prefix if they only typed the 4 characters.
export function normalizePass(input: string): string {
  let s = input.trim().toUpperCase().replace(/\s+/g, '')
  if (!s) return s
  if (!s.includes('-') && /^[A-Z0-9]{4}$/.test(s)) s = `EXTRA-${s}`
  return s
}

// Local-only pass code, used when Supabase isn't configured (local dev) so the
// app is still fully playable without a backend.
function genLocalCode(): string {
  const alphabet = '23456789ABCDEFGHJKMNPQRSTUVWXYZ'
  let c = ''
  for (let i = 0; i < 4; i++) c += alphabet[Math.floor(Math.random() * alphabet.length)]
  return `EXTRA-${c}`
}

type ProfileRow = { id: string; pass_code: string; first_name: string; last_name: string }
const fromRow = (r: ProfileRow): Profile => ({
  id: r.id,
  passCode: r.pass_code,
  firstName: r.first_name,
  lastName: r.last_name,
})

/** Create a new profile (server-side pass code), remember it, and return it. */
export async function createProfile(first: string, last: string): Promise<Profile> {
  const firstName = first.trim()
  const lastName = last.trim()
  if (!firstName || !lastName) throw new Error('First and last name are required.')

  if (!supabase) {
    // No backend (local dev): make a self-contained local profile.
    const p: Profile = { id: crypto.randomUUID(), passCode: genLocalCode(), firstName, lastName }
    store(p)
    return p
  }

  const { data, error } = await supabase.rpc('create_profile', {
    p_first: firstName,
    p_last: lastName,
  })
  if (error) throw new Error(friendlyRpcError(error))
  const row = (Array.isArray(data) ? data[0] : data) as ProfileRow | null
  if (!row) throw new Error('Could not create your profile — please try again.')
  const p = fromRow(row)
  store(p)
  return p
}

/**
 * Re-attach to an existing profile by its pass code. Returns the profile, or
 * null if the code doesn't match one. Requires the live site (needs the server).
 */
export async function loginByPass(passInput: string): Promise<Profile | null> {
  const pass = normalizePass(passInput)
  if (!pass) throw new Error('Enter your Player Pass.')

  if (!supabase) {
    throw new Error('Re-attaching with a Player Pass needs the live site.')
  }

  const { data, error } = await supabase.rpc('get_profile_by_pass', { p_pass: pass })
  if (error) throw new Error(friendlyRpcError(error))
  // A function returning a composite row yields an all-null object (not SQL
  // null) when there's no match, so check for a real id, not just truthiness.
  const row = (Array.isArray(data) ? data[0] : data) as ProfileRow | null
  if (!row || !row.id) return null
  const p = fromRow(row)
  store(p)
  return p
}

// Friendlier messages for the common "not set up yet" states, matching the
// tone of resetScores in scores.ts.
function friendlyRpcError(error: { code?: string; message: string }): string {
  const code = error.code
  if (
    code === 'PGRST202' ||
    code === '42P01' ||
    /could not find|schema cache|function|relation .* does not exist/i.test(error.message)
  ) {
    return 'Profiles aren’t set up yet — run supabase/profiles.sql once in Supabase, then try again.'
  }
  return error.message
}
