import { useSyncExternalStore } from 'react'
import { supabase } from './supabase'

// Player identity — a lightweight "Player Pass". A profile is a first + last
// name plus a short, friendly pass code (e.g. EXTRA-4F7Q) generated by the
// server. It's remembered in this browser so a player isn't re-prompted, and
// the pass code lets them re-attach to the same profile on another device.
// No accounts, no passwords, no PII beyond the name they already give.

export type Profile = {
  id: string
  passCode: string
  firstName: string
  lastName: string
}

const KEY = 'extra-mile-profile'
const LEGACY_KEY = 'extra-mile-player' // pre-profiles name-only storage

// A tiny reactive store so the whole app (header badge, game page) reflects
// sign-in / sign-out immediately, without a page reload. `current` caches the
// loaded profile; `listeners` are React subscribers via useProfile().
let current: Profile | null | undefined // undefined = not loaded yet
const listeners = new Set<() => void>()
const emit = () => listeners.forEach((l) => l())

function readStorage(): Profile | null {
  try {
    const raw = localStorage.getItem(KEY)
    if (!raw) return null
    const p = JSON.parse(raw) as Profile
    if (p && p.id && p.passCode && p.firstName && p.lastName) return p
    return null
  } catch {
    return null
  }
}

export function getProfile(): Profile | null {
  if (current === undefined) current = readStorage()
  return current
}

function store(p: Profile): void {
  current = p
  try {
    localStorage.setItem(KEY, JSON.stringify(p))
    localStorage.removeItem(LEGACY_KEY)
  } catch {
    /* private mode / storage disabled — the app still works for this session */
  }
  emit()
}

export function clearProfile(): void {
  current = null
  try {
    localStorage.removeItem(KEY)
  } catch {
    /* ignore */
  }
  emit()
}

/** React hook: the current profile, re-rendering on sign-in / sign-out. */
export function useProfile(): Profile | null {
  return useSyncExternalStore(
    (cb) => {
      listeners.add(cb)
      return () => listeners.delete(cb)
    },
    getProfile,
    getProfile,
  )
}

export function fullName(p: Profile): string {
  return `${p.firstName} ${p.lastName}`.trim()
}

// Normalize whatever the player types into a pass code: uppercase, trim, drop
// stray spaces, and add the EXTRA- prefix if they only typed the 4 characters.
export function normalizePass(input: string): string {
  let s = input.trim().toUpperCase().replace(/\s+/g, '')
  if (!s) return s
  if (!s.includes('-') && /^[A-Z0-9]{4}$/.test(s)) s = `EXTRA-${s}`
  return s
}

// A recovery PIN: exactly 4 digits. Used with First + Last to reconnect a
// player who lost their pass, and to keep two same-named people distinct.
export function normalizePin(input: string): string {
  return input.replace(/\D/g, '').slice(0, 4)
}
export function isValidPin(input: string): boolean {
  return /^[0-9]{4}$/.test(input)
}

// Local-only pass code, used when Supabase isn't configured (local dev) so the
// app is still fully playable without a backend.
function genLocalCode(): string {
  const alphabet = '23456789ABCDEFGHJKMNPQRSTUVWXYZ'
  let c = ''
  for (let i = 0; i < 4; i++) c += alphabet[Math.floor(Math.random() * alphabet.length)]
  return `EXTRA-${c}`
}

type ProfileRow = { id: string; pass_code: string; first_name: string; last_name: string }
const fromRow = (r: ProfileRow): Profile => ({
  id: r.id,
  passCode: r.pass_code,
  firstName: r.first_name,
  lastName: r.last_name,
})

/**
 * Create a new profile. The player picks a 4-digit PIN; First + Last + PIN must
 * be unique, so two same-named people stay distinct and either can recover their
 * pass later. Returns the profile (with its generated pass code); the PIN is
 * never returned or stored on the device.
 */
export async function createProfile(first: string, last: string, pin: string): Promise<Profile> {
  const firstName = first.trim()
  const lastName = last.trim()
  if (!firstName || !lastName) throw new Error('First and last name are required.')
  if (!isValidPin(pin)) throw new Error('Pick a 4-digit PIN (numbers only).')

  if (!supabase) {
    // No backend (local dev): make a self-contained local profile.
    const p: Profile = { id: crypto.randomUUID(), passCode: genLocalCode(), firstName, lastName }
    store(p)
    return p
  }

  const { data, error } = await supabase.rpc('create_profile', {
    p_first: firstName,
    p_last: lastName,
    p_pin: pin,
  })
  if (error) throw new Error(friendlyRpcError(error))
  const row = (Array.isArray(data) ? data[0] : data) as ProfileRow | null
  if (!row || !row.id) throw new Error('Could not create your profile — please try again.')
  const p = fromRow(row)
  store(p)
  return p
}

/**
 * Re-attach to an existing profile by its pass code. Returns the profile, or
 * null if the code doesn't match one. Requires the live site (needs the server).
 */
export async function loginByPass(passInput: string): Promise<Profile | null> {
  const pass = normalizePass(passInput)
  if (!pass) throw new Error('Enter your Player Pass.')

  if (!supabase) {
    throw new Error('Re-attaching with a Player Pass needs the live site.')
  }

  const { data, error } = await supabase.rpc('get_profile_by_pass', { p_pass: pass })
  if (error) throw new Error(friendlyRpcError(error))
  // A function returning a composite row yields an all-null object (not SQL
  // null) when there's no match, so check for a real id, not just truthiness.
  const row = (Array.isArray(data) ? data[0] : data) as ProfileRow | null
  if (!row || !row.id) return null
  const p = fromRow(row)
  store(p)
  return p
}

/**
 * Recover a profile with First + Last + PIN — the fallback when a player has
 * lost their Player Pass. Returns the profile, or null if nothing matches.
 * Requires the live site (needs the server).
 */
export async function loginByNamePin(
  first: string,
  last: string,
  pin: string,
): Promise<Profile | null> {
  const firstName = first.trim()
  const lastName = last.trim()
  if (!firstName || !lastName) throw new Error('Enter your first and last name.')
  if (!isValidPin(pin)) throw new Error('Enter your 4-digit PIN.')

  if (!supabase) {
    throw new Error('Reconnecting with your name and PIN needs the live site.')
  }

  const { data, error } = await supabase.rpc('get_profile_by_name_pin', {
    p_first: firstName,
    p_last: lastName,
    p_pin: pin,
  })
  if (error) throw new Error(friendlyRpcError(error))
  const row = (Array.isArray(data) ? data[0] : data) as ProfileRow | null
  if (!row || !row.id) return null
  const p = fromRow(row)
  store(p)
  return p
}

// Friendlier messages for the common "not set up yet" and known states,
// matching the tone of resetScores in scores.ts.
function friendlyRpcError(error: { code?: string; message: string }): string {
  const code = error.code
  if (/name\+pin taken/i.test(error.message)) {
    return 'Someone with that name already uses that PIN. If that’s you, tap “Lost your pass?” to reconnect. If not, pick a different 4-digit PIN.'
  }
  if (/unauthorized/i.test(error.message)) {
    return 'Admin password didn’t match the one in Supabase → app_config.'
  }
  if (/admin password not set/i.test(error.message)) {
    return 'Admin password isn’t set — add it in Supabase → Table Editor → app_config (reset_password).'
  }
  if (
    code === 'PGRST202' ||
    code === '42P01' ||
    /could not find|schema cache|function|relation .* does not exist/i.test(error.message)
  ) {
    return 'Player admin isn’t set up yet — run supabase/admin-players.sql once in Supabase, then try again.'
  }
  return error.message
}

// ---------------------------------------------------------------------------
// Admin player management (gated by the admin password server-side). These call
// the SECURITY DEFINER functions in supabase/admin-players.sql.
// ---------------------------------------------------------------------------

export type AdminProfile = {
  id: string
  firstName: string
  lastName: string
  passCode: string
  createdAt: string
  scoreCount: number
}

/** Search players by name or pass code (admin). Returns [] if not configured. */
export async function adminFindProfiles(pw: string, query: string): Promise<AdminProfile[]> {
  if (!supabase) return []
  const { data, error } = await supabase.rpc('admin_find_profiles', { pw, q: query })
  if (error) throw new Error(friendlyRpcError(error))
  return ((data ?? []) as Array<{
    id: string
    first_name: string
    last_name: string
    pass_code: string
    created_at: string
    score_count: number
  }>).map((r) => ({
    id: r.id,
    firstName: r.first_name,
    lastName: r.last_name,
    passCode: r.pass_code,
    createdAt: r.created_at,
    scoreCount: Number(r.score_count),
  }))
}

/** Issue a new Player Pass for a player (keeps all their data). Returns it. */
export async function adminResetPass(pw: string, profileId: string): Promise<string> {
  if (!supabase) throw new Error('This needs the live site.')
  const { data, error } = await supabase.rpc('admin_reset_pass', { pw, p_id: profileId })
  if (error) throw new Error(friendlyRpcError(error))
  return String(data)
}

/** Set a new 4-digit PIN for a player (keeps all their data). */
export async function adminSetPin(pw: string, profileId: string, newPin: string): Promise<void> {
  if (!supabase) throw new Error('This needs the live site.')
  if (!isValidPin(newPin)) throw new Error('PIN must be 4 digits.')
  const { error } = await supabase.rpc('admin_set_pin', { pw, p_id: profileId, new_pin: newPin })
  if (error) throw new Error(friendlyRpcError(error))
}

/** Delete a player's account AND all their data. Returns scores removed. */
export async function adminDeleteProfile(pw: string, profileId: string): Promise<number> {
  if (!supabase) throw new Error('This needs the live site.')
  const { data, error } = await supabase.rpc('admin_delete_profile', { pw, p_id: profileId })
  if (error) throw new Error(friendlyRpcError(error))
  return (data as number) ?? 0
}
