import { useSyncExternalStore } from 'react'
import { supabase } from './supabase'

// Player identity — a lightweight "Player Pass". A profile is a first + last
// name plus a short, friendly pass code (e.g. EXTRA-4F7Q) generated by the
// server, plus a 4-digit PIN they choose. No passwords, no PII beyond the name.

export type Profile = {
  id: string
  passCode: string
  firstName: string
  lastName: string
}

// The signed-in session lives ONLY in memory — it is intentionally NOT
// persisted, so a page refresh or a closed tab drops it and the player is
// returned to the login page. An idle timer also ends the session after
// INACTIVITY_MS of no activity. This is the "accounts lock on refresh / close /
// 15 min idle" behavior.
const INACTIVITY_MS = 15 * 60 * 1000

let current: Profile | null = null
let idleTimer: ReturnType<typeof setTimeout> | undefined
const listeners = new Set<() => void>()
const emit = () => listeners.forEach((l) => l())

function armIdleTimer(): void {
  if (idleTimer) clearTimeout(idleTimer)
  idleTimer = setTimeout(() => signOut(), INACTIVITY_MS)
}

export function getProfile(): Profile | null {
  return current
}

/** Begin a session for this profile (called only after successful auth). */
export function signIn(p: Profile): void {
  current = p
  armIdleTimer()
  emit()
}

/** End the session (sign out, idle timeout, or lock). */
export function signOut(): void {
  current = null
  if (idleTimer) clearTimeout(idleTimer)
  idleTimer = undefined
  emit()
}

// Kept name for callers that "sign out" (e.g. the header button).
export const clearProfile = signOut

/** Reset the inactivity timer on user activity (no-op when signed out). */
export function touchSession(): void {
  if (current) armIdleTimer()
}

/** React hook: the current session profile, re-rendering on sign-in / sign-out. */
export function useProfile(): Profile | null {
  return useSyncExternalStore(
    (cb) => {
      listeners.add(cb)
      return () => listeners.delete(cb)
    },
    getProfile,
    getProfile,
  )
}

export function fullName(p: Profile): string {
  return `${p.firstName} ${p.lastName}`.trim()
}

// Normalize whatever the player types into a pass code: uppercase, trim, drop
// stray spaces, and add the EXTRA- prefix if they only typed the 4 characters.
export function normalizePass(input: string): string {
  let s = input.trim().toUpperCase().replace(/\s+/g, '')
  if (!s) return s
  if (!s.includes('-') && /^[A-Z0-9]{4}$/.test(s)) s = `EXTRA-${s}`
  return s
}

// A recovery PIN: exactly 4 digits. Used with First + Last to reconnect a
// player who lost their pass, and to keep two same-named people distinct.
export function normalizePin(input: string): string {
  return input.replace(/\D/g, '').slice(0, 4)
}
export function isValidPin(input: string): boolean {
  return /^[0-9]{4}$/.test(input)
}

// Local-only pass code, used when Supabase isn't configured (local dev) so the
// app is still fully playable without a backend.
function genLocalCode(): string {
  const alphabet = '23456789ABCDEFGHJKMNPQRSTUVWXYZ'
  let c = ''
  for (let i = 0; i < 4; i++) c += alphabet[Math.floor(Math.random() * alphabet.length)]
  return `EXTRA-${c}`
}

type ProfileRow = {
  id: string
  pass_code: string
  first_name: string
  last_name: string
  must_set_pin?: boolean
}
const fromRow = (r: ProfileRow): Profile => ({
  id: r.id,
  passCode: r.pass_code,
  firstName: r.first_name,
  lastName: r.last_name,
})

// Login result: the profile plus whether an admin reset means the player must
// now choose a personal PIN before playing.
export type LoginResult = { profile: Profile; mustSetPin: boolean }

/**
 * Create a new profile. The player picks a 4-digit PIN; First + Last + PIN must
 * be unique, so two same-named people stay distinct and either can recover their
 * pass later. Returns the profile (with its generated pass code); the PIN is
 * never returned or stored on the device.
 */
export async function createProfile(first: string, last: string, pin: string): Promise<Profile> {
  const firstName = first.trim()
  const lastName = last.trim()
  if (!firstName || !lastName) throw new Error('First and last name are required.')
  if (!isValidPin(pin)) throw new Error('Pick a 4-digit PIN (numbers only).')

  if (!supabase) {
    // No backend (local dev): make a self-contained local profile.
    return { id: crypto.randomUUID(), passCode: genLocalCode(), firstName, lastName }
  }

  const { data, error } = await supabase.rpc('create_profile', {
    p_first: firstName,
    p_last: lastName,
    p_pin: pin,
  })
  if (error) throw new Error(friendlyRpcError(error))
  const row = (Array.isArray(data) ? data[0] : data) as ProfileRow | null
  if (!row || !row.id) throw new Error('Could not create your profile — please try again.')
  return fromRow(row)
}

/**
 * Re-attach to an existing profile by its pass code. Returns the profile, or
 * null if the code doesn't match one. Requires the live site (needs the server).
 */
export async function loginByPass(passInput: string): Promise<LoginResult | null> {
  const pass = normalizePass(passInput)
  if (!pass) throw new Error('Enter your Player Pass.')

  if (!supabase) {
    throw new Error('Re-attaching with a Player Pass needs the live site.')
  }

  const { data, error } = await supabase.rpc('get_profile_by_pass', { p_pass: pass })
  if (error) throw new Error(friendlyRpcError(error))
  // A function returning a composite row yields an all-null object (not SQL
  // null) when there's no match, so check for a real id, not just truthiness.
  const row = (Array.isArray(data) ? data[0] : data) as ProfileRow | null
  if (!row || !row.id) return null
  return { profile: fromRow(row), mustSetPin: !!row.must_set_pin }
}

/**
 * Recover a profile with First + Last + PIN — the fallback when a player has
 * lost their Player Pass. Returns the profile, or null if nothing matches.
 * Requires the live site (needs the server).
 */
export async function loginByNamePin(
  first: string,
  last: string,
  pin: string,
): Promise<LoginResult | null> {
  const firstName = first.trim()
  const lastName = last.trim()
  if (!firstName || !lastName) throw new Error('Enter your first and last name.')
  if (!isValidPin(pin)) throw new Error('Enter your 4-digit PIN.')

  if (!supabase) {
    throw new Error('Reconnecting with your name and PIN needs the live site.')
  }

  const { data, error } = await supabase.rpc('get_profile_by_name_pin', {
    p_first: firstName,
    p_last: lastName,
    p_pin: pin,
  })
  if (error) throw new Error(friendlyRpcError(error))
  const row = (Array.isArray(data) ? data[0] : data) as ProfileRow | null
  if (!row || !row.id) return null
  return { profile: fromRow(row), mustSetPin: !!row.must_set_pin }
}

/**
 * Player self-service: set a new personal PIN by presenting the current pass
 * code. Used right after an admin reset to clear the "must set PIN" flag.
 */
export async function setOwnPin(passCode: string, newPin: string): Promise<void> {
  if (!isValidPin(newPin)) throw new Error('Pick a 4-digit PIN (numbers only).')
  if (!supabase) throw new Error('This needs the live site.')
  const { error } = await supabase.rpc('set_own_pin', { p_pass: passCode, p_new_pin: newPin })
  if (error) throw new Error(friendlyRpcError(error))
}

// Friendlier messages for the common "not set up yet" and known states,
// matching the tone of resetScores in scores.ts.
function friendlyRpcError(error: { code?: string; message: string }): string {
  const code = error.code
  if (/name\+pin taken/i.test(error.message)) {
    return 'Someone with that name already uses that PIN. If that’s you, tap “Lost your pass?” to reconnect. If not, pick a different 4-digit PIN.'
  }
  if (/unauthorized/i.test(error.message)) {
    return 'Admin password didn’t match the one in Supabase → app_config.'
  }
  if (/admin password not set/i.test(error.message)) {
    return 'Admin password isn’t set — add it in Supabase → Table Editor → app_config (reset_password).'
  }
  if (
    code === 'PGRST202' ||
    code === '42P01' ||
    /could not find|schema cache|function|relation .* does not exist/i.test(error.message)
  ) {
    return 'Player admin isn’t set up yet — run supabase/admin-players.sql once in Supabase, then try again.'
  }
  return error.message
}

// ---------------------------------------------------------------------------
// Admin player management (gated by the admin password server-side). These call
// the SECURITY DEFINER functions in supabase/admin-players.sql.
// ---------------------------------------------------------------------------

export type AdminProfile = {
  id: string
  firstName: string
  lastName: string
  passCode: string
  createdAt: string
  scoreCount: number
}

/** Search players by name or pass code (admin). Returns [] if not configured. */
export async function adminFindProfiles(pw: string, query: string): Promise<AdminProfile[]> {
  if (!supabase) return []
  const { data, error } = await supabase.rpc('admin_find_profiles', { pw, q: query })
  if (error) throw new Error(friendlyRpcError(error))
  return ((data ?? []) as Array<{
    id: string
    first_name: string
    last_name: string
    pass_code: string
    created_at: string
    score_count: number
  }>).map((r) => ({
    id: r.id,
    firstName: r.first_name,
    lastName: r.last_name,
    passCode: r.pass_code,
    createdAt: r.created_at,
    scoreCount: Number(r.score_count),
  }))
}

/** Issue a new Player Pass for a player (keeps all their data). Returns it. */
export async function adminResetPass(pw: string, profileId: string): Promise<string> {
  if (!supabase) throw new Error('This needs the live site.')
  const { data, error } = await supabase.rpc('admin_reset_pass', { pw, p_id: profileId })
  if (error) throw new Error(friendlyRpcError(error))
  return String(data)
}

/** Set a new 4-digit PIN for a player (keeps all their data). */
export async function adminSetPin(pw: string, profileId: string, newPin: string): Promise<void> {
  if (!supabase) throw new Error('This needs the live site.')
  if (!isValidPin(newPin)) throw new Error('PIN must be 4 digits.')
  const { error } = await supabase.rpc('admin_set_pin', { pw, p_id: profileId, new_pin: newPin })
  if (error) throw new Error(friendlyRpcError(error))
}

/** Delete a player's account AND all their data. Returns scores removed. */
export async function adminDeleteProfile(pw: string, profileId: string): Promise<number> {
  if (!supabase) throw new Error('This needs the live site.')
  const { data, error } = await supabase.rpc('admin_delete_profile', { pw, p_id: profileId })
  if (error) throw new Error(friendlyRpcError(error))
  return (data as number) ?? 0
}
